services:

  db:
    image: postgres
    container_name: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  db:
